# Generated by Django 4.2.13 on 2024-05-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="duration",),
    ]
